apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-ip
  labels:
    app: curdle-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: curdle-frontend
