name: Push Image to Registry

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for deployed image."
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
      - uses: actions/checkout@v3
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Dockerfile
        run: docker build . -t ${{secrets.DOCKER_USER}}/curdle-frontend:latest -t ${{secrets.DOCKER_USER}}/curdle-frontend:${{github.event.inputs.tag}}
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/curdle-frontend --all-tags
